name: workouts
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.15.4
  cloud_functions: ^4.6.5

  # Network
  dio: ^5.4.0
  url_launcher: ^6.2.4

  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # Drift
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.9.0

  # Core
  easy_localization: ^3.0.3
  auto_route: ^7.8.4
  get_it: ^7.6.7
  uuid: ^4.3.3

  # Utils
  dart_date: ^1.3.2
  flutter_keyboard_visibility: ^6.0.0

  # UI
  auto_size_text_field: ^2.2.2
  flutter_slidable: ^3.0.1

  # Annotation
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

dependency_overrides:
  path: 1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Code generation
  freezed: ^2.4.7
  build_runner: ^2.4.8
  drift_dev: ^2.15.0
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
      - "assets/images/"
      - "assets/translations/"
      - "assets/files/"